{
 "title": "All natural events",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Map",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select coordinates[1] as latitude,\ncoordinates[0] as longitude, \n(select count(*) from geometry sub where sub.event_id = evt.id) as magnitude,\nevt.title as name,\ncat.title as category,\ns.id as source_device,\nevt.id as event_code,\ntype,\ndt\nfrom event evt\nleft join geometry geo ON (event_id = evt.id)\nleft join event_source es ON (es.event_id=evt.id)\nleft join source s ON (es.source_id=s.id)\nleft join category cat ON (evt.category_id=cat.id_txt)\nwhere dt > $__timeFrom()  and dt < $__timeTo() \nand cat.id = 10"
    },
    {
     "rawSql": "select coordinates[1] as latitude,\ncoordinates[0] as longitude, \n(select count(*) from geometry sub where sub.event_id = evt.id) as magnitude,\nevt.title as name,\ncat.title as category,\ns.id as source_device,\nevt.id as event_code,\ntype,\ndt\nfrom event evt\nleft join geometry geo ON (event_id = evt.id)\nleft join event_source es ON (es.event_id=evt.id)\nleft join source s ON (es.source_id=s.id)\nleft join category cat ON (evt.category_id=cat.id_txt)\nwhere dt > $__timeFrom()  and dt < $__timeTo() \nand cat.id = 12"
    },
    {
     "rawSql": "select coordinates[1] as latitude,\ncoordinates[0] as longitude, \n(select count(*) from geometry sub where sub.event_id = evt.id) as magnitude,\nevt.title as name,\ncat.title as category,\ns.id as source_device,\nevt.id as event_code,\ntype,\ndt\nfrom event evt\nleft join geometry geo ON (event_id = evt.id)\nleft join event_source es ON (es.event_id=evt.id)\nleft join source s ON (es.source_id=s.id)\nleft join category cat ON (evt.category_id=cat.id_txt)\nwhere dt > $__timeFrom()  and dt < $__timeTo() \nand cat.id = 15"
    },
    {
     "rawSql": "select coordinates[1] as latitude,\ncoordinates[0] as longitude, \n(select count(*) from geometry sub where sub.event_id = evt.id) as magnitude,\nevt.title as name,\ncat.title as category,\ns.id as source_device,\nevt.id as event_code,\ntype,\ndt\nfrom event evt\nleft join geometry geo ON (event_id = evt.id)\nleft join event_source es ON (es.event_id=evt.id)\nleft join source s ON (es.source_id=s.id)\nleft join category cat ON (evt.category_id=cat.id_txt)\nwhere dt > $__timeFrom()  and dt < $__timeTo() \nand cat.id = 8"
    },
    {
     "rawSql": "select coordinates[1] as latitude,\ncoordinates[0] as longitude, \n(select count(*) from geometry sub where sub.event_id = evt.id) as magnitude,\nevt.title as name,\ncat.title as category,\ns.id as source_device,\nevt.id as event_code,\ntype,\ndt\nfrom event evt\nleft join geometry geo ON (event_id = evt.id)\nleft join event_source es ON (es.event_id=evt.id)\nleft join source s ON (es.source_id=s.id)\nleft join category cat ON (evt.category_id=cat.id_txt)\nwhere dt > $__timeFrom()  and dt < $__timeTo() \nand cat.id = 9"
    },
    {
     "rawSql": "SELECT geometry[0] as latitude,\ngeometry[1] as longitude,\ninstrument, confidence, satellite, bright_ti4, bright_ti4 as magnitude, distance, time\nFROM public.fire\nwhere time > $__timeFrom()  and time < $__timeTo()\n"
    },
    {
     "rawSql": "SELECT  geometry[0] as latitude,\ngeometry[1] as longitude,\ncode, magnitude, depth, distance, time\nFROM public.quake\nwhere time > $__timeFrom()  and time < $__timeTo()\n"
    }
   ]
  },
  {
   "title": "# Events/date",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "rawSql": "with al as (\nselect 'fire' as category, count(*) as evnt, to_date(TO_CHAR(time, 'YYYY-MM-DD'), 'YYYY-MM-DD') as time\nfrom fire group by to_date(TO_CHAR(time, 'YYYY-MM-DD'), 'YYYY-MM-DD'), category\nunion\nselect 'quake' as category, count(*) as evnt, to_date(TO_CHAR(time, 'YYYY-MM-DD'), 'YYYY-MM-DD') as time\nfrom quake group by to_date(TO_CHAR(time, 'YYYY-MM-DD'), 'YYYY-MM-DD'), category\nunion\nselect evt.category_id as category, count(evt.id) as evnt, to_date(TO_CHAR(dt, 'YYYY-MM-DD'), 'YYYY-MM-DD') as time\nfrom event evt\njoin geometry geo ON (event_id = evt.id)\ngroup by evt.category_id, to_date(TO_CHAR(dt, 'YYYY-MM-DD'), 'YYYY-MM-DD') \n)\nselect category, evnt, time from al\n  where time > $__timeFrom()  and time < $__timeTo()"
    }
   ]
  },
  {
   "title": "# Events/categories",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 5 },
   "targets": [
    {
     "rawSql": "with al as (\nselect 'fire' as category, count(*) as evnt, time \nfrom fire group by time, category\n\tunion\nselect 'quake' as category, count(*) as evnt, time \nfrom quake group by time, category\n\tunion \nselect evt.category_id as category, count(evt.id) as evnt, dt as time\nfrom event evt\njoin geometry geo ON (event_id = evt.id)\ngroup by evt.category_id, dt \n\t)\n\tselect category, evnt, time from al \n  where time > $__timeFrom()  and time < $__timeTo() \n\t\tand category is not null\n"
    }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "WITH al as (select \nevt.title as name,\ncat.title as category,\ns.id as source_device,\nevt.id as event_code,\nmax(coalesce(magnitudevalue, 1.0)) as magnitude, max(coalesce(magnitudeunit, '')) as magnitudeunit, max(dt) as dt\nfrom event evt\nleft join geometry geo ON (event_id = evt.id)\nleft join event_source es ON (es.event_id=evt.id)\nleft join source s ON (es.source_id=s.id)\nleft join category cat ON (evt.category_id=cat.id_txt)\ngroup by evt.title, cat.title, s.id, evt.id\nUNION\nselect '--' as name, 'fire' as category, instrument as source_device, satellite as event_code, 1.0 as magnitude, '' as unit, time as dt from fire\nUNION\nselect code as name, 'quake' as category, '' as source_device, code as event_code, magnitude, 'ML' as unit, time as dt from quake\n)\nselect * from al\nwhere dt > $__timeFrom()  and dt < $__timeTo() "
    }
   ]
  }
 ]
}